---
include:
  - board: seeeduino_xiao_ble
    shield: ergonautkb_neo_left
  - board: seeeduino_xiao_ble
    shield: ergonautkb_neo_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: ergonautkb_neo_left
    artifact-name: ergonautkb_neo_left_debug
  - board: seeeduino_xiao_ble
    shield: ergonautkb_neo_right
    artifact-name: ergonautkb_neo_right_debug
